"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Copy, Check, Share2, RefreshCw, Loader2 } from "lucide-react";
import { IdeaBlob } from "./IdeaBlob";
import AssistantMarkdown from "@/components/chat/AssistantMarkdown";
import { ChatMessage } from "@/types";

interface IdeaSummaryProps {
  messages: ChatMessage[];
  summary: string | null;
  loading: boolean;
  duration?: number; // elapsed seconds
  onReset: () => void;
}

function formatDuration(secs: number): string {
  if (secs <= 0) return "—";
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  if (m === 0) return `${s}s`;
  return s === 0 ? `${m}m` : `${m}m ${s}s`;
}

const FALLBACK_SUMMARY = `Session Summary

Your idea shows real potential. Here's what came out of the session:

Strengths
• Clear problem-solution fit with validated demand
• Differentiated value proposition
• Scalable business model

Areas to Strengthen
• Sharpen the competitive positioning
• Define a concrete go-to-market entry point
• Validate pricing assumptions with real users

Recommended Next Steps
1. Run 10 user interviews to stress-test core assumptions
2. Identify your single unfair advantage over alternatives
3. Ship the smallest version that proves your value hypothesis

Generated by Acela Idea Mode`;

export default function IdeaSummary({ messages, summary, loading, duration = 0, onReset }: IdeaSummaryProps) {
  const router = useRouter();
  const [copied, setCopied] = useState(false);

  const displaySummary = summary ?? FALLBACK_SUMMARY;
  const messageCount = messages.filter(
    (m) => m.role === "user" || m.role === "assistant"
  ).length;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(displaySummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleShare = () => {
    if (typeof navigator !== "undefined" && navigator.share) {
      navigator.share({ title: "Idea Mode Session Summary", text: displaySummary });
    }
  };

  return (
    <div className="relative flex-1 overflow-hidden bg-base">

      {/* ── Background blobs ──────────────────────────── */}
      <div className="absolute -top-32 -left-32 pointer-events-none" style={{ color: "var(--primary)" }}>
        <IdeaBlob variant="lg" opacity={0.18} />
      </div>
      <div className="absolute -bottom-40 -right-32 pointer-events-none" style={{ color: "var(--card)" }}>
        <IdeaBlob variant="lg" opacity={0.25} animationDelay="2s" />
      </div>

      {/* ── Scrollable content ────────────────────────── */}
      <div className="relative z-10 h-full overflow-y-auto">
        <div className="flex flex-col items-center gap-8 max-w-2xl mx-auto px-6 py-10">

          {/* Header */}
          <div className="flex flex-col gap-4 text-center">
            <h1 className="text-4xl md:text-5xl font-black text-primary">
              Session Complete!
            </h1>
            <p className="text-lg text-text-2">
              Your ideas have been captured and organized
            </p>
          </div>

          {/* Summary box */}
          <div className="w-full border-[3px] border-text-2 bg-surface p-8 rounded-[10px]">
            <h2 className="text-xs font-bold uppercase text-text-faint tracking-widest mb-4">
              Your Summary
            </h2>

            {loading ? (
              <div className="flex items-center justify-center gap-3 py-8 text-text-faint">
                <Loader2 className="w-5 h-5 animate-spin" />
                <span className="text-sm">Generating your summary…</span>
              </div>
            ) : (
              <AssistantMarkdown content={displaySummary} />
            )}
          </div>

          {/* Action buttons — disabled while loading */}
          <div className="flex flex-col gap-4 w-full">
            <button
              onClick={handleCopy}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 bg-primary font-bold px-8 py-4 text-base rounded-[10px] transition-colors hover:bg-primary-hover focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
              style={{ color: "var(--base)" }}
            >
              {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
              {copied ? "Copied to clipboard" : "Copy to clipboard"}
            </button>

            <button
              onClick={handleShare}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 border-[3px] border-text-2 bg-transparent font-bold px-8 py-4 text-base text-text-1 rounded-[10px] transition-colors hover:bg-surface focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Share2 className="w-5 h-5" />
              Share
            </button>

            <button
              onClick={() => { router.push("/?mode=idea"); onReset(); }}
              className="w-full flex items-center justify-center gap-2 border-[3px] border-primary bg-transparent font-bold px-8 py-4 text-base text-primary rounded-[10px] transition-colors hover:bg-primary focus:outline-none"
              style={{ transition: "background 0.15s, color 0.15s" }}
              onMouseEnter={(e) => { e.currentTarget.style.color = "var(--base)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.color = "var(--primary)"; }}
            >
              <RefreshCw className="w-4 h-4" />
              Start New Session
            </button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 gap-4 w-full pt-8" style={{ borderTop: "1px solid var(--text-faint)" }}>
            <div className="text-center">
              <div className="text-3xl font-black text-primary">{messageCount || "—"}</div>
              <div className="text-xs uppercase text-text-faint mt-1 tracking-wider">Messages</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-black text-primary">{formatDuration(duration)}</div>
              <div className="text-xs uppercase text-text-faint mt-1 tracking-wider">Duration</div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
